# -*- coding: utf-8 -*-
"""Vigenere (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bXsqkDi1mqoEHromfADyUkzpeEzeTxCu
"""

!pip install Flask pyngrok flask-cors

!ngrok config add-authtoken #Code19383729294972test818383maybe17373

from flask import Flask, request, jsonify
from pyngrok import ngrok
from flask_cors import CORS

# Initialize Flask
flask_app = Flask(__name__)

CORS(flask_app)

# Vigenere Cipher Function
def vigenere_cipher(text, key, mode='encrypt'):
    result = []
    key_length = len(key)
    key_nums = [ord(k) - ord('A') for k in key.upper()]  # Key converted to numbers
    text_nums = [ord(c) - ord('A') for c in text.upper() if c.isalpha()]  # Text converted to numbers
    for i, num in enumerate(text_nums):
        key_shift = key_nums[i % key_length]  # Cyclically use key characters
        if mode == 'encrypt':
            new_num = (num + key_shift) % 26  # Modular addition
        elif mode == 'decrypt':
            new_num = (num - key_shift + 26) % 26  # Modular subtraction
        result.append(chr(new_num + ord('A')))  # Convert back to letter

    final_result = []
    non_alpha_index = 0
    for c in text:
        if c.isalpha():
            final_result.append(result[non_alpha_index])
            non_alpha_index += 1
        else:
            final_result.append(c)
    return ''.join(final_result)

# Flask route to process encryption/decryption via web
@flask_app.route("/vigenere", methods=["POST"])
def vigenere_web():
    data = request.json
    message = data.get("message", "").upper()
    key = data.get("key", "").upper()
    mode = data.get("mode", "encrypt")
    result = vigenere_cipher(message, key, mode=mode)
    return jsonify({"result": result})

# Mulai ngrok
public_url = ngrok.connect(5000)
print(f"Public URL: {public_url}")

# Jalankan Flask
flask_app.run(port=5000)

